### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by Ozeitis** [Nobelz/RateMyProfessorAPI#4]
Hey so I did extensive testing on a few devices and the API no longer finds professors for me anymore. I thought it was an IP blocking issue maybe but tried different networks and no luck.

**Comment by Nobelz** [comment]
Hey @Ozeitis,
You are correct. I just tested it and upon closer look at the website code I believe it is because they have changed the way they have formatted their queries, which results in the entire API being broken. I will have to look at it after finals; alternatively, you can also look at it.

The problem is with `professorquery.json`. Other `.json` files may be affected, but as of now I cannot isolate the issue.

**Comment by Ozeitis** [comment]
#5

**Comment by Nobelz** [comment]
Your pull request should've fixed the issue, can you confirm?

**Comment by Ozeitis** [comment]
> Your pull request should've fixed the issue, can you confirm?

I am using this myself and can confirm it does fix the issue :). No problems yet. I use this often so I will report if I find any.
